/// Format configuration for all supported output formats (FFmpeg 8.1.1 essentials build compatible)
#[allow(dead_code)]
pub struct FormatConfig {
    pub codec: &'static str,
    pub extension: &'static str,
    pub lossless: bool,
    pub default_bitrate: Option<u32>,
    pub max_bitrate: Option<u32>,
    pub default_sample_rate: Option<u32>,
    pub max_sample_rate: Option<u32>,
    pub supports_bit_depth: bool,
    pub extra_args: Vec<&'static str>,
    pub format_flag: Option<&'static str>,
}

/// Get format configuration for a given format string
pub fn get_format_config(format: &str) -> FormatConfig {
    match format {
        "mp3" => FormatConfig {
            codec: "libmp3lame",
            extension: "mp3",
            lossless: false,
            default_bitrate: Some(320),
            max_bitrate: Some(320),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
            format_flag: None,
        },
        "aac" => FormatConfig {
            codec: "aac",
            extension: "aac",
            lossless: false,
            default_bitrate: Some(256),
            max_bitrate: Some(512),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(96000),
            supports_bit_depth: false,
            extra_args: vec![],
            format_flag: None,
        },
        "flac" => FormatConfig {
            codec: "flac",
            extension: "flac",
            lossless: true,
            default_bitrate: None,
            max_bitrate: None,
            default_sample_rate: Some(48000),
            max_sample_rate: Some(192000),
            supports_bit_depth: true,
            extra_args: vec![],
            format_flag: None,
        },
        "wav" => FormatConfig {
            codec: "pcm_s16le",
            extension: "wav",
            lossless: true,
            default_bitrate: None,
            max_bitrate: None,
            default_sample_rate: Some(48000),
            max_sample_rate: Some(192000),
            supports_bit_depth: true,
            extra_args: vec![],
            format_flag: None,
        },
        "m4a" => FormatConfig {
            codec: "aac",
            extension: "m4a",
            lossless: false,
            default_bitrate: Some(256),
            max_bitrate: Some(512),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(96000),
            supports_bit_depth: false,
            extra_args: vec![],
            format_flag: Some("ipod"),
        },
        "ogg" => FormatConfig {
            codec: "libvorbis",
            extension: "ogg",
            lossless: false,
            default_bitrate: Some(256),
            max_bitrate: Some(500),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
            format_flag: None,
        },
        "opus" => FormatConfig {
            codec: "opus",
            extension: "opus",
            lossless: false,
            default_bitrate: Some(128),
            max_bitrate: Some(510),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec!["-strict", "-2"],
            format_flag: None,
        },
        "alac" => FormatConfig {
            codec: "alac",
            extension: "m4a",
            lossless: true,
            default_bitrate: None,
            max_bitrate: None,
            default_sample_rate: Some(48000),
            max_sample_rate: Some(192000),
            supports_bit_depth: true,
            extra_args: vec![],
            format_flag: Some("ipod"),
        },
        "ac3" => FormatConfig {
            codec: "ac3",
            extension: "ac3",
            lossless: false,
            default_bitrate: Some(448),
            max_bitrate: Some(640),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
            format_flag: None,
        },
        "aiff" => FormatConfig {
            codec: "pcm_s16be",
            extension: "aiff",
            lossless: true,
            default_bitrate: None,
            max_bitrate: None,
            default_sample_rate: Some(48000),
            max_sample_rate: Some(192000),
            supports_bit_depth: true,
            extra_args: vec![],
            format_flag: None,
        },
        "eac3" => FormatConfig {
            codec: "eac3",
            extension: "eac3",
            lossless: false,
            default_bitrate: Some(640),
            max_bitrate: Some(1536),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
            format_flag: None,
        },
        "mp2" => FormatConfig {
            codec: "mp2",
            extension: "mp2",
            lossless: false,
            default_bitrate: Some(256),
            max_bitrate: Some(384),
            default_sample_rate: Some(44100),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
            format_flag: None,
        },
        "wavpack" => FormatConfig {
            codec: "wavpack",
            extension: "wv",
            lossless: true,
            default_bitrate: None,
            max_bitrate: None,
            default_sample_rate: Some(48000),
            max_sample_rate: Some(192000),
            supports_bit_depth: true,
            extra_args: vec![],
            format_flag: None,
        },
        _ => FormatConfig {
            codec: "libmp3lame",
            extension: "mp3",
            lossless: false,
            default_bitrate: Some(320),
            max_bitrate: Some(320),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
            format_flag: None,
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_all_formats_have_config() {
        let formats = [
            "mp3", "aac", "flac", "wav", "m4a", "ogg", "opus", "alac",
            "ac3", "aiff", "eac3", "mp2", "wavpack",
        ];
        for fmt in formats {
            let config = get_format_config(fmt);
            assert!(!config.codec.is_empty(), "Format {} has empty codec", fmt);
            assert!(!config.extension.is_empty(), "Format {} has empty extension", fmt);
        }
    }
}
