/// Format configuration for all 21 supported output formats
#[allow(dead_code)]
pub struct FormatConfig {
    pub codec: &'static str,
    pub extension: &'static str,
    pub lossless: bool,
    pub default_bitrate: Option<u32>,
    pub max_bitrate: Option<u32>,
    pub default_sample_rate: Option<u32>,
    pub max_sample_rate: Option<u32>,
    pub supports_bit_depth: bool,
    pub extra_args: Vec<&'static str>,
}

/// Get format configuration for a given format string
pub fn get_format_config(format: &str) -> FormatConfig {
    match format {
        "mp3" => FormatConfig {
            codec: "libmp3lame",
            extension: "mp3",
            lossless: false,
            default_bitrate: Some(320),
            max_bitrate: Some(320),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
        },
        "aac" => FormatConfig {
            codec: "aac",
            extension: "aac",
            lossless: false,
            default_bitrate: Some(256),
            max_bitrate: Some(512),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(96000),
            supports_bit_depth: false,
            extra_args: vec![],
        },
        "flac" => FormatConfig {
            codec: "flac",
            extension: "flac",
            lossless: true,
            default_bitrate: None,
            max_bitrate: None,
            default_sample_rate: Some(48000),
            max_sample_rate: Some(192000),
            supports_bit_depth: true,
            extra_args: vec![],
        },
        "wav" => FormatConfig {
            codec: "pcm_s16le",
            extension: "wav",
            lossless: true,
            default_bitrate: None,
            max_bitrate: None,
            default_sample_rate: Some(48000),
            max_sample_rate: Some(192000),
            supports_bit_depth: true,
            extra_args: vec![],
        },
        "m4a" => FormatConfig {
            codec: "aac",
            extension: "m4a",
            lossless: false,
            default_bitrate: Some(256),
            max_bitrate: Some(512),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(96000),
            supports_bit_depth: false,
            extra_args: vec![],
        },
        "ogg" => FormatConfig {
            codec: "libvorbis",
            extension: "ogg",
            lossless: false,
            default_bitrate: Some(256),
            max_bitrate: Some(500),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
        },
        "opus" => FormatConfig {
            codec: "libopus",
            extension: "opus",
            lossless: false,
            default_bitrate: Some(128),
            max_bitrate: Some(510),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
        },
        "alac" => FormatConfig {
            codec: "alac",
            extension: "m4a",
            lossless: true,
            default_bitrate: None,
            max_bitrate: None,
            default_sample_rate: Some(48000),
            max_sample_rate: Some(192000),
            supports_bit_depth: true,
            extra_args: vec![],
        },
        "wma" => FormatConfig {
            codec: "wmav2",
            extension: "wma",
            lossless: false,
            default_bitrate: Some(192),
            max_bitrate: Some(320),
            default_sample_rate: Some(44100),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
        },
        "ac3" => FormatConfig {
            codec: "ac3",
            extension: "ac3",
            lossless: false,
            default_bitrate: Some(448),
            max_bitrate: Some(640),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
        },
        "aiff" => FormatConfig {
            codec: "pcm_s16be",
            extension: "aiff",
            lossless: true,
            default_bitrate: None,
            max_bitrate: None,
            default_sample_rate: Some(48000),
            max_sample_rate: Some(192000),
            supports_bit_depth: true,
            extra_args: vec![],
        },
        "eac3" => FormatConfig {
            codec: "eac3",
            extension: "eac3",
            lossless: false,
            default_bitrate: Some(640),
            max_bitrate: Some(1536),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
        },
        "dts" => FormatConfig {
            codec: "dca",
            extension: "dts",
            lossless: false,
            default_bitrate: Some(1536),
            max_bitrate: Some(1536),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
        },
        "mp2" => FormatConfig {
            codec: "mp2",
            extension: "mp2",
            lossless: false,
            default_bitrate: Some(320),
            max_bitrate: Some(384),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
        },
        "wavpack" => FormatConfig {
            codec: "wavpack",
            extension: "wv",
            lossless: true,
            default_bitrate: None,
            max_bitrate: None,
            default_sample_rate: Some(48000),
            max_sample_rate: Some(192000),
            supports_bit_depth: true,
            extra_args: vec![],
        },
        "tta" => FormatConfig {
            codec: "tta",
            extension: "tta",
            lossless: true,
            default_bitrate: None,
            max_bitrate: None,
            default_sample_rate: Some(48000),
            max_sample_rate: Some(96000),
            supports_bit_depth: true,
            extra_args: vec![],
        },
        "aptx" => FormatConfig {
            codec: "libaptx",
            extension: "aptx",
            lossless: false,
            default_bitrate: Some(352),
            max_bitrate: Some(352),
            default_sample_rate: Some(44100),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
        },
        "sbc" => FormatConfig {
            codec: "sbc",
            extension: "sbc",
            lossless: false,
            default_bitrate: Some(328),
            max_bitrate: Some(328),
            default_sample_rate: Some(44100),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
        },
        "truehd" => FormatConfig {
            codec: "truehd",
            extension: "truehd",
            lossless: true,
            default_bitrate: None,
            max_bitrate: None,
            default_sample_rate: Some(48000),
            max_sample_rate: Some(192000),
            supports_bit_depth: true,
            extra_args: vec![],
        },
        "mlp" => FormatConfig {
            codec: "mlp",
            extension: "mlp",
            lossless: true,
            default_bitrate: None,
            max_bitrate: None,
            default_sample_rate: Some(48000),
            max_sample_rate: Some(192000),
            supports_bit_depth: true,
            extra_args: vec![],
        },
        "dfpwm" => FormatConfig {
            codec: "dfpwm",
            extension: "dfpwm",
            lossless: false,
            default_bitrate: None,
            max_bitrate: None,
            default_sample_rate: Some(48000),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
        },
        _ => FormatConfig {
            codec: "libmp3lame",
            extension: "mp3",
            lossless: false,
            default_bitrate: Some(320),
            max_bitrate: Some(320),
            default_sample_rate: Some(48000),
            max_sample_rate: Some(48000),
            supports_bit_depth: false,
            extra_args: vec![],
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_all_formats_have_config() {
        let formats = [
            "mp3", "aac", "flac", "wav", "m4a", "ogg", "opus", "alac",
            "wma", "ac3", "aiff", "eac3", "dts", "mp2", "wavpack", "tta",
            "aptx", "sbc", "truehd", "mlp", "dfpwm",
        ];
        for fmt in formats {
            let config = get_format_config(fmt);
            assert!(!config.codec.is_empty(), "Format {} has empty codec", fmt);
            assert!(!config.extension.is_empty(), "Format {} has empty extension", fmt);
        }
    }
}
